[package]
name = "smullerijkalender"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
icalendar = "0.17.5"
reqwest = "0.12.12"
serde_json = "1.0.138"
tokio = "1.43.0"
actix-web = "4"
actix-files = "0.6.6"
csv = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
